[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remappings for dependencies
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts/security/=lib/openzeppelin-contracts/contracts/utils/",
    "openzeppelin-contracts/access/=lib/openzeppelin-contracts/contracts/access/",
    "openzeppelin-contracts/token/=lib/openzeppelin-contracts/contracts/token/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
